olx_clone/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

olx_clone/item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('new/', views.new, name='new'),
]

olx_clone/olx_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

olx_clone/core/models.py
from django.db import models

# Create your models here.

olx_clone/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email','password1', 'password2']
        

    username = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "Your Username",
        "class": "w-full py-4 px-6 rounded-xl"
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        "placeholder": "Your Email address",
        "class": "w-full py-4 px-6 rounded-xl"
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Your password",
        "class": "w-full py-4 px-6 rounded-xl"
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Repeat password",
        "class": "w-full py-4 px-6 rounded-xl"
    }))


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "Your Username",
        "class": "w-full py-4 px-6 rounded-xl"
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Your password",
        "class": "w-full py-4 px-6 rounded-xl"
    }))

olx_clone/core/views.py
from django.shortcuts import render, redirect, HttpResponse

from item.models import Category, Item
from .forms import SignupForm

# Create your views here.
def index(request):
    items = Item.objects.filter(is_sold=False)[:6]
    categories = Category.objects.all()

    context = {
        'categories': categories,
        'items': items,
    }

    return render(request, 'core/index.html', context)


def contact(request):
    return render(request, 'core/contact.html')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('core:login')
    else:
        form = SignupForm()
        
    context = {
        'form': form,
    }
    
    return render(request, 'core/signup.html', context)

olx_clone/templates/core/contact.html
{% extends 'base.html' %}

{% block title %} Contact {% endblock %}

{% block content %}
<div class="w-2/3 my-6 mx-auto bg-gray-100 rounded-xl p-6">
    <h1 class="mb-4">The contact page</h1>
</div>
{% endblock %}

olx_clone/templates/core/index.html
{% extends 'base.html' %}

{% block title %} Welcome {{ request.user.username }} {% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center font-semibold ">Newest Items</h2>

        <div class="grid grid-cols-3 gap-3">
        {% for item in items %}
            <div>
                <a href="{% url 'item:detail' item.id %}">
                    <div>
                        <img src="{{ item.image.url }}" alt="" class="rounded-t-xl">
                    </div>
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl mb-2">{{ item.name }}</h2>
                        <p class="text-gray-500 ">Price: &#8377;{{ item.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center font-semibold ">Categories</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div>
                    <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl mb-2">{{ category.name }}</h2>
                            <p class="text-gray-500 ">{{ category.items.count }} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

olx_clone/templates/core/login.html
{% extends 'base.html' %}

{% block title %} Log in {% endblock %}

{% block content %}
    <div class="w-1/2 my-6 mx-auto bg-gray-100 rounded-xl p-6">
        <h1 class="mb-6 text-3xl">Login</h1>
        <form action="." method="POST">
            {% csrf_token %}

            <div class="mb-3">
                <label class="inline-block mb-2">Username: </label> <br>
                {{ form.username }} <br>
                <label class="inline-block mb-2">Password: </label> <br>
                {{ form.password }} <br>
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                    
                </div>
            {% endif %}

            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
        </form>
    </div>
{% endblock %}

olx_clone/templates/core/signup.html
{% extends 'base.html' %}

{% block title %} SignUp {% endblock %}

{% block content %}
    <div class="w-1/2 my-6 mx-auto bg-gray-100 rounded-xl p-6">
        <h1 class="mb-6 text-3xl">Sign up</h1>
        <form action="." method="POST">
            {% csrf_token %}

            <div class="mb-3">
                <label class="inline-block mb-2">Username: </label> <br>
                {{ form.username }} <br>
                <label class="inline-block mb-2">Email: </label> <br>
                {{ form.email }} <br>
                <label class="inline-block mb-2">Password: </label> <br>
                {{ form.password1 }} <br>
                <label class="inline-block mb-2">Repeat Password: </label> <br>
                {{ form.password2 }} <br>
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                    
                </div>
            {% endif %}

            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
        </form>
    </div>
{% endblock %}