olx_clone/conversation/urls.py
from django.urls import path

from . import views


app_name = 'conversation'
urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail_conversation, name='detail_conversation'), 
    path('new/<int:item_pk>/', views.new_conversation, name='new')

]

olx_clone/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

olx_clone/dashboard/urls.py
from django.urls import path

from . import views


app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='dashboard'),
]

olx_clone/item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('new/', views.new, name='new'),
]

olx_clone/olx_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

olx_clone/templates/includes/footer.html
<footer class="p-6 bg-gray-800">
    <div class="w-full flex justify-between">
    <div class="w-2/3 pr-10">
        <h3 class="mb-5 font-semibold text-gray-400">About Us</h3>
        <p class="text-lg text-gray-500">OLX is a prominent online marketplace that revolutionized the way people buy and sell goods and services across the globe. Launched in 2006, OLX quickly became one of the most popular platforms for local classified advertisements. With a user-friendly interface and a vast array of categories, OLX has made it simple for individuals and businesses alike to connect with prospective buyers and sellers within their local communities. <br> OLX has undoubtedly transformed the way people buy and sell items locally, creating a global platform for classified advertisements. Its user-friendly interface, diverse categories, and focus on local interactions have made it an essential tool for countless individuals and businesses around the world. As the digital landscape continues to evolve, OLX is likely to remain a vital player in the online marketplace, empowering users to connect and transact in a convenient and efficient manner.</p>
    </div>
    <div class="w-1/3">
        <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
        <ul class="space-y-2">
            <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
            <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
            <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy Policy</a></li>
            <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms and Conditions</a></li>
        </ul>
    </div>
    </div>
    <div class="flex justify-center align-center">
        <p class="text-white">Copyright © 2023 @anonymouscoder1511 All Rights Reserved.</p>
    </div>
</footer>

olx_clone/templates/includes/navbar.html
<nav class="p-6 flex justify-between items-center border-b border-gray-200">
    <a href="/" class="text-xl font-semibold ml-6">OLX</a>
    <div class="w-1/2">
        <form action="{% url 'item:items' %}" method="GET">
            <div class="relative border rounded-full px-6 border-gray-500">
                <input type="text" class="bg-white h-14 w-full rounded-lg focus:outline-none hover:cursor-pointer"
                    name="query" value="{{ query }}" placeholder="Search Items here...">
                <button class="absolute top-4 right-4"><i class="fa fa-search text-gray-400 hover:text-gray-500"></i></button>
            </div>
        </form>
    </div>
    <div class="space-x-6">
        <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New Item</a>
        <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>
        {% if request.user.is_authenticated %}
        <a href="{% url 'conversation:inbox' %}"
            class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700 ">Inbox</a>
        <a href="{% url 'dashboard:dashboard' %}"
            class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700 ">Dashboard</a>
        <a href="{% url 'core:logout' %}"><i class="fa-solid fa-arrow-right-from-bracket text-xl"></i></a>
        {% else %}
        <a href="{% url 'core:signup' %}"
            class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700 ">Sign Up</a>
        <a href="{% url 'core:login' %}"
            class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700 ">Log In</a>
        {% endif %}
    </div>
</nav>