olx_clone/conversation/urls.py
from django.urls import path

from . import views


app_name = 'conversation'
urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail_conversation, name='detail_conversation'), 
    path('new/<int:item_pk>/', views.new_conversation, name='new')

]

olx_clone/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

olx_clone/item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('new/', views.new, name='new'),
]

olx_clone/olx_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

olx_clone/item/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name


class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True, max_length=255)
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    price = models.FloatField()
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name

olx_clone/item/forms.py
from django import forms

from .models import Item

INPUT_CLASSES = "w-full py-4 px-6 rounded-xl border"

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image',)

        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image','is_sold')

        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

olx_clone/item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from .models import Item, Category
from .forms import NewItemForm, EditItemForm
# Create your views here.


def items(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)

    if category_id:
        items = items.filter(category_id=category_id)

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))

    context = {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id)
    }

    return render(request, 'item/items.html', context)



def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[:3]

    context = {
        'item': item,
        'related_items': related_items
    }
    return render(request, 'item/detail.html', context)



@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('item:detail', pk=item.id)
        
    else:
        form = NewItemForm()

    context = {
        'form': form,
        'title' : 'Add a new item'
    }
    
    return render(request, 'item/form.html', context)


@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    
    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect('item:detail', pk=item.id)
        
    else:
        form = EditItemForm(instance=item)

    context = {
        'form': form,
        'title' : 'Edit item'
    }
    
    return render(request, 'item/form.html', context)


@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:dashboard')

olx_clone/templates/item/detail.html
{% extends 'base.html' %} 

{% block title %} {{ item.name }} {% endblock %} 

{% block content %}
<div class="grid grid-cols-6 gap-2">
    <div class="col-span-3 flex justify-center">
        <img src="{{ item.image.url }}" alt="" class="rounded-xl" />
    </div>
    <div class="col-span-3 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
        <p class="text-gray-500"><strong>Price: {{ item.price }}</strong></p>
        <p class="text-gray-500">
            <strong>Seller: {{ item.created_by.username }}</strong>
        </p>

        {% if item.description %}
        <p class="text-gray-700">
            <strong class="text-gray-500">Description:</strong>
            {{ item.description }}
        </p>
        {% endif %}
        {% if request.user == item.created_by %}
            <div class="mt-6 p-6 bg-white rounded-xl">
                <p>This is Your Item</p>
                <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Edit</a>
                <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
            </div>
         {% else %}
            <a href="{% url 'conversation:new' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">
                Contact Seller
            </a>
        {% endif %}
    </div>
</div>
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center font-semibold ">Related Items</h2>

    <div class="grid grid-cols-3 gap-3">
    {% for item in related_items %}
        <div>
            <a href="{% url 'item:detail' item.id %}">
                <div>
                    <img src="{{ item.image.url }}" alt="" class="rounded-t-xl">
                </div>
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl mb-2">{{ item.name }}</h2>
                    <p class="text-gray-500 ">Price: &#8377;{{ item.price }}</p>
                </div>
            </a>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

olx_clone/templates/item/form.html
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
<div class="w-3/4 my-6 mx-auto bg-gray-100 rounded-xl p-6">

    <h1 class="mb-6 text-3xl ">{{ title }}</h1>
    
    <form action="." method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="space-y-4 text-lg">
            {{ form.as_p }}
        </div>
        
        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
            {{ field.errors }}
            {% endfor %}
            
            {{ form.non_field_errors }}
            
        </div>
        {% endif %}
        
        <button class="mt-4 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Add Item</button>
    </form>
</div>
{% endblock %}

olx_clone/templates/item/items.html
{% extends 'base.html' %}

{% block title %} Items {% endblock %}

{% block content %}

<div class="pb-6 grid grid-cols-4 gap-4">
    <div class="col-span-1 px-6 py-4 bg-gray-100 rounded-xl">
        <form action="{% url 'item:items' %}" method="GET">
            <div class="w-full">
                <div class="relative">
                    <input type="text" class="bg-white h-14 w-full px-12 rounded-lg focus:outline-none hover:cursor-pointer" name="query" value="{{ query }}" placeholder="Find Items here...">
                    <button class="absolute top-4 left-4"><i class=" fa fa-search text-gray-400 "></i></button>
                </div>
            </div>
        </form>
        <hr class="my-6"/>
        <p class="font-semibold mb-2">Categories</p>
        <ul>
            
            {% for category in categories %}
                <li class="py-4 px-4 rounded-xl {% if category.id == category_id %} bg-gray-300 {% endif %} hover:bg-gray-200">
                    <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                </li>
            {% endfor %}
                
        </ul>

        <hr class="my-6"/>
        <p class="font-semibold ">Clear filter</p>
        <ul>
            <li>
                <a href="{% url 'item:items' %}" class="mt-2 py-2 px-6 inline-block bg-yellow-500 text-lg text-white rounded-xl">Reset</a>
            </li>
        </ul>
    </div>
    <div class="col-span-3">
        <div class="px-6 py-6 rounded-xl bg-gray-100">
            {% if items %}
            <h2 class="mb-12 text-2xl text-center font-semibold ">Items</h2>

            <div class="grid grid-cols-3 gap-3">
                {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" alt="" class="rounded-t-xl">
                        </div>
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl mb-2">{{ item.name }}</h2>
                            <p class="text-gray-500 ">Price: &#8377;{{ item.price }}</p>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
            {% else %}
            <div class="flex items-center justify-center">
                <h1 class="font-semibold text-3xl">No Items in this filter.</h1>
            </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}